### PR TITLE
Add recaptcha security

### PR DESCRIPTION
**Pull request by JackHowa**
Sorry to hear your fame is costing you. Thought recaptcha might be helpful to monitor in case you're getting spam. (Also it's a pretty interesting [story](https://www.npr.org/2020/05/22/860884062/recaptcha-and-duolingo-luis-von-ahn) in and of itself.) Anyway, if you create a site key, you should be able to monitor this better. Let me know if you need help once you get up and running. 

https://developers.google.com/recaptcha/docs/v3#top_of_page

You may also need to apply for a higher rate of traffic. This is a link for that https://developers.google.com/recaptcha/docs/faq#are-there-any-qps-or-daily-limits-on-my-use-of-recaptcha

- it's mostly just monitoring traffic and potentially malicious requests 
- to do more complex logic and prevent responses, it'd take a backend to verify if you're interested @nicksawhney https://dev.to/kumar_abhirup/implementing-google-recaptcha-with-react-and-node-js-1jgf

Screen Shot 2021-01-21 at 23 17 54
Screen Shot 2021-01-21 at 23 20 08

### CODE REVIEW

**Comment by nicksawhney** [comment]
Just wanna say, this is awesome and I'd love to have it in an alternative branch of the site.

 I'm thinking we maintain a relatively original-looking version of the site, and have another branch where we can go absolutely wild with everything people want to contribute -- styling, different images and overlays (like people have been asking for on twitter), changing image placement, all the rest! That version could become a more general open-source web based meme creation app. Would love anyone's thoughts!

**Comment by JackHowa** [comment]
@nicksawhney yeah I'm not sure. the meme generator was cut-off? I created an issue for what's next #20

**Comment by nicksawhney** [comment]
What if we implemented capcha on the main branch but made it an optional flag based on an environment variable. Makes it easy to deploy and customize with Heroku, and could be a part of the automation system discussed in #25 . 

If so, I'm happy to make these changes, or I can assign it to you @JackHowa (or anyone else who wants it)

**Comment by JackHowa** [comment]
can close this as we're archiving this

**Pull request closed without merging**
