### PR TITLE
Fix Licensing section in README.md

### PR DESCRIPTION
**Pull request by samarmohan**

### CODE REVIEW

**Comment by samarmohan** [comment]
All I did was fix the header. What license should I add?

**Comment by nicksawhney** [comment]
GNU General Public License please! Thanks a lot! (I'd suggest rebasing with the current version of `main`)

**Comment by nicksawhney** [comment]
Actually, let's table this for the night -- I need to look into proper licensing for this site and don't want to make any rash decisions!

**Comment by nicksawhney** [comment]
Licensing discussion in #23

**Comment by samarmohan** [comment]
Close?

**Pull request closed without merging**
